FROM --platform=linux/arm64 arm64v8/golang:1.17.6-alpine3.15 as builder
ENV GOARCH arm
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN GOGC=off CGO_ENABLED=0 go build -v -o prometheus_bot


FROM --platform=linux/arm64 arm64v8/alpine:3.15.0 as alpine
RUN apk add --no-cache --update ca-certificates tzdata
EXPOSE 9087
WORKDIR /
COPY --from=builder /app/prometheus_bot /prometheus_bot
USER nobody
CMD ["/prometheus_bot"]
