name: Build amd64 docker image version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_REPOSITORY: gru.ocir.io/grwidfxfmi4f/prometheus-bot
  ARCH: amd64

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_LOGIN }}
          password: ${{ secrets.OCI_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{env.IMAGE_REPOSITORY}}:latest
            ${{env.IMAGE_REPOSITORY}}:build${{ github.run_number }}

      - name: Dump context
        if: always()
        uses: raniellyferreira/ghaction-dump-context@v1
